services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - ./:/app     # Mount the current directory to the container
    command: hugo server --bind 0.0.0.0 -D
    # network_mode: host

